### ISSUE TITLE
ConnectionString options might be case sensitive 

### ISSUE THREAD

**Issue by mat-mcloughlin** [EventStore/EventStore-Client-NodeJS#114]
@danjamescrosby has reported that if he uses uppercase `T` in `Tls` that it's not being correctly picked up an option. Where as lowercase is fine

![image](https://user-images.githubusercontent.com/2362687/103872915-ed4e2400-50c6-11eb-88f3-f00d94d97320.png)

**Comment by George-Payne** [comment]
fixed by #109

**Comment by mat-mcloughlin** [comment]
thanks, wasn't aware :+1:
