### ISSUE TITLE
Unable to create a subscription for  eventStore Cloud 

### ISSUE THREAD

**Issue by wellington-aquino-dev** [EventStore/EventStore-Client-NodeJS#131]
I'm having an issue connecting to EventStore cloud and creating a subscription 
the same code work on my local env but not in the cloud

```
const connectionStr = “esdb://localhost:2113?tls=false”
    const client = EventStoreDBClient.connectionString(connectionStr)
    const received: ResolvedEvent[] = []
    const sub = client.subscribeToAll()
    sub.on(‘error’, err => console.log(err, err?.message))
    sub.on(‘close’, () => {})
    sub.on(‘data’, evt => {
      console.log(evt)
    }) 
```
this works but if I change the connection string to the cloud ` esdb://<<couldendpoit>>:2113?tls=true`

I get this error, 

```
node:43812) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: Access Denied
    at Object.convertToCommandError (.../node_modules/@eventstore/db-client/dist/utils/CommandError.js:246:20)
    at ClientReadableStreamImpl.<anonymous> (.../node_modules/@eventstore/db-client/dist/utils/OneWaySubscription.js:32:38)
    at ClientReadableStreamImpl.emit (events.js:315:20)
    at Object.onReceiveStatus (.../node_modules/@grpc/grpc-js/build/src/client.js:327:28)
    at Object.onReceiveStatus (.../node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at .../node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

```

**Comment by George-Payne** [comment]
Hi Wellington, 

By default, reading from `$all` requires a user with access to it (for example, `$admin`).

As your local db is running in `insecure` mode, it does not use any authentication or authorisation ([more info here](https://developers.eventstore.com/server/v20/server/security/configuration.html#running-without-security)).

You can pass credentials in one of two ways:

- Setting the default credentials for the client:
   _(used for all requests unless overridden)_
   - In the connection string:
     `"esdb://admin:changeit@id.mesdb.eventstore.cloud:2113"`
   - via the third parameter of the client constructor:
     `new EventStoreDBClient(_, _, { username: "admin", password: "changeit" });`
- Setting the credentials for the single request:
  _(used for just this request. overrides default credentials.)_
  ```
  client.subscribeToAll({ 
    credentials: { 
      username: "admin", 
      password: "changeit" 
    } 
  });
  ```

**Comment by wellington-aquino-dev** [comment]
Thanks for the quick response, I was able to connect :)
