### ISSUE TITLE
Cannot connect as described in the README

### ISSUE THREAD

**Issue by alexlawrence** [EventStore/EventStore-Client-NodeJS#133]
I have a single EventStoreDB node running locally as Docker container and want to connect to it. I can verify the instance is running and available by accessing the web interface. However,  I cannot connect with the Node.js client as shown in the README.

When instantiating the class `EventStoreDBClient` and subsequently performing an action, the error message "Error: 14 UNAVAILABLE: No connection established" is logged. However, when using the static factory function as described in the [docs](https://developers.eventstore.com/clients/grpc/getting-started/connecting.html), it works correctly.

My setup:
- OS: Linux (Ubuntu)
- Node.js: v15.2.0
- Module syntax: ESM
- EventStoreDB running as local docker container

Independent of my issue, the example seems to be incomplete. While the code is correctly attempting to connect, the exemplary usage function `simpleTest()` is never executed.

**Comment by YoEight** [comment]
Can you share how you started your docker container please?

**Comment by alexlawrence** [comment]
I followed the [docs](https://developers.eventstore.com/server/v20/server/installation/docker.html#run-with-docker) on this and tried both ways that are described there.

This means, I tried it with both of the following commands:

`docker run --name esdb-node -it -p 2113:2113 -p 1113:1113 eventstore/eventstore:latest --insecure --run-projections=All`
`docker run --name esdb-node -it -p 2113:2113 -p 1113:1113 eventstore/eventstore:latest --insecure --run-projections=All --enable-external-tcp --enable-atom-pub-over-http`

Actually, I am using docker-compose, but I don't think this should make a difference.

What I didn't try so far is to connect from within the Docker container itself (using `localhost`). So far, I either tried to connect from the host or another container that has access to the EventStore container. Still, the factory function variant works for both of those scenarios.

**Comment by YoEight** [comment]
The last part of your comment is hard to understand. What do you mean by it worked on both scenarios? Do you mean you managed to connect with the NodeJS client?

I propose to make sure that in the most simple use case, you are able to connect to a server while using the nodejs client. 

The goal is to determine if the client is at fault or your docker configuration.

**Comment by alexlawrence** [comment]
Sorry for my cryptic comment. Yes, I always managed to connect with the Node.js client by using the factory syntax `EventStoreDBClient.connectionString('...');` I mentioned this in my first comment. Sorry if it wasn't clear enough.

It did only not work for me when using the constructor function (`new EventStoreDBClient()`). However, I found out what the problem was. I was missing the "insecure" flag for the `ChannelCredentialOptions` constructor argument. :facepalm: 

This issue is therefore invalid and can be closed.
