### ISSUE TITLE
Stream subscriptions should allow for backpressure

### ISSUE THREAD

**Issue by Eadword** [EventStore/EventStore-Client-NodeJS#141]
I noticed this because I had a couple of events where one is expected to be processed completely before the next one runs and then checking the typing it seems the handler function takes the form `on(event: "data", listener: (event: E) => void): this`.

Not sure if it is in scope for the subscription to await a promise returned by the handler, but it is IMO important for back-pressure to prevent overwhelming a service or database with requests.

An impromptu solution on my end would be to use an async worker "thread" or something, but then I run the risk of my application's memory overflowing if the database gets behind.

This is mostly relevant for me right now as I am working with an all stream subscription that is parsing through a bunch of older events and a slightly-less-jury-rigged solution would be to read form the all stream until the end and then switch to a subscription. And this may be one of the only good options depending on how the GRPC connection works.

**Comment by George-Payne** [comment]
Hi Matthew, 

Subscriptions return a stream, so you should be able to apply backpressure in all the usual ways. 

Unfortunately the doc comments on `subscribeToStream` and `subscribeToAll` are wrong (fixed in #142), but there is a third optional parameter to set your `ReadableOptions` https://nodejs.org/api/stream.html#stream_new_stream_readable_options

>  the subscription to await a promise returned by the handler,

This is probably easiest to do using an async iterator:

```ts
const subscription = client.subscribeToAll(
  {
    fromPosition: START,
    filter: excludeSystemEvents(),
  },
  {
      // its an object mode stream, so this means to buffer 5 events (default is 16)
      highWaterMark: 5,
  }
);

for await (const event of subscription) {
    // stream will fill up its buffer while it waits for the async function, then pause itself.
    // next event wont be processed until the promise is resolved.
    await doSomethingAsyncWithTheEvent(event);
}
```

You could also do something with pause / resume if you want a more manual approach.

**Comment by Eadword** [comment]
Oh that is interesting. I was using the `.on` which was partially a carry over from using the old TCP library. I assume `.on` does not buffer as well?

I definitely did not realize it was an AsyncGenerator-like and I am very happy to see it is. High water mark here makes a lot of sense and this looks like a solid approach.

**Comment by George-Payne** [comment]
> I assume .on does not buffer as well?

No, `on` will just subscribe you to the event, and by default, it just spits them out:

https://nodejs.org/api/stream.html#stream_readable_streams
> In flowing mode, data is read from the underlying system automatically and provided to an application as quickly as possible using events via the EventEmitter interface.

The only additions on top of a `ReadableStream` are:

- `unsubscribe`:
    Allows you to cleanly cancel the stream.

- `ack` & `nack`
   Sends the ack and nack requests back up the stream.
   
   
 Everything else is vanilla `ReadableStream` in object mode.
 
 
 (Its technically a `TransformStream`, but is already hooked up on the write end, so can be treated as a `ReadableStream`)

**Comment by Eadword** [comment]
I think that answers all of my questions, thank you!
