### ISSUE TITLE
Unicode Issue

### ISSUE THREAD

**Issue by anex** [EventStore/EventStore-Client-NodeJS#144]
Hi,

Hope you can help us with the following:

We are experiencing an issue with unicode, we append a event to stream with the following data:

`{ name: CC ‐ 1830 }`

When we read that event from the stream we got a string as data instead an object, and the value of the string is the following:

`'{"name":"CC \u0010 1830"}'`

We can parse that string to JSON because `\u0010` is not valid.

You can reproduce the issue with the following script: https://codeshare.io/G7nk6L

**Comment by George-Payne** [comment]
Hi Carlos, 

Thank you for the bug report, 

The fix is out in [v1.0.2](https://www.npmjs.com/package/@eventstore/db-client/v/1.0.2)
