### ISSUE TITLE
Support for Create/Update Stream Metadata

### ISSUE THREAD

**Issue by wellington-aquino-dev** [EventStore/EventStore-Client-NodeJS#148]
The current client implementation does not provide an API for creating or update the Stream Metadata which is required when we want to set a $maxAge or $maxCount for any given Stream

https://developers.eventstore.com/server/v20.10/docs/streams/metadata-and-reserved-names.html#stream-metadata

**Comment by George-Payne** [comment]
Hi Wellington,

Thanks for the issue, this is now available in [v1.1.0](https://www.npmjs.com/package/@eventstore/db-client/v/1.1.0)

**Comment by wellington-aquino-dev** [comment]
Thanks George, for the quick reply. We'll update and test it out :)
