### ISSUE TITLE
Monitoring persistent subscriptions: Make Client.resolveUri public (?)

### ISSUE THREAD

**Issue by bjorm** [EventStore/EventStore-Client-NodeJS#156]
We are monitoring our persistent subscriptions by periodically accessing the HTTP endpoint `/subscriptions` on a node. In a clustered environment it is not obvious which node that should be. Even though it is declared private we are calling [`Client.resolveUri`](https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/src/Client/index.ts#L310) because it does exactly what we need. 

- Is there an easier/better way?
- Is it a problem to make `Client.resolveUri` public?
- Are there plans for something like [PersistentSubscriptionsManager](https://developers.eventstore.com/clients/dotnet/5.0/subscriptions/persistent-subscription-manager.html#create-the-manager-instance) for this client?

**Comment by hayley-jean** [comment]
Hi @bjorm,

We do intend on adding the ability to list persistent subscriptions to the gRPC clients, but can't tell you when that will be yet

**Comment by George-Payne** [comment]
Hi @bjorm,

[`v3.2.0` has now been released](https://github.com/EventStore/EventStore-Client-NodeJS/releases/tag/v3.2.0), adding the ability to list persistent subscriptions.

You can find sample usage for it here:
https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/samples/persistent-subscriptions.ts#L330-L385
