### ISSUE TITLE
NotHandled is NotHandled

### ISSUE THREAD

**Issue by vtajzich** [EventStore/EventStore-Client-NodeJS#160]
**Describe the bug**
Use NodeJS client (currently using version 1.2.1).
When an application is starting, it tries to create a persistent subscription and connect to it (when subscription already exists, it handles the error code and continue).

Specific method used: ```createPersistentSubscription(streamName: string, groupName: string, settings: PersistentSubscriptionSettings, options?: BaseOptions): Promise<void>;```

Sometimes it returns weird error:

```
Error: 2 UNKNOWN: Envelope callback expected either PersistentSubscriptionConfirmation or NotHandled, received NotHandled instead at Object.convertToCommandError (node_modules/@eventstore/db-client/dist/utils/CommandError.js:282:12) at ClientDuplexStreamImpl.<anonymous> (node_modules/@eventstore/db-client/dist/utils/TwoWaySubscription.js:34:38) at ClientDuplexStreamImpl.emit (events.js:315:20) at Object.onReceiveStatus
```

**To Reproduce**
1. Use NodeJS client
2. Try to create subscription (even it already exists)
3. Sometimes it returns error code 2 and error `NotHandled, received NotHandled instead`

**Expected behavior**
It returns no error when subscription doesn't exists or error code 6 (ALREADY_EXISTS) when subscription exists.

**Actual behavior**
Return error code 2 (see description)

**Config/Logs/Screenshots**
```
Error: 2 UNKNOWN: Envelope callback expected either PersistentSubscriptionConfirmation or NotHandled, received NotHandled instead at Object.convertToCommandError (node_modules/@eventstore/db-client/dist/utils/CommandError.js:282:12) at ClientDuplexStreamImpl.<anonymous> (node_modules/@eventstore/db-client/dist/utils/TwoWaySubscription.js:34:38) at ClientDuplexStreamImpl.emit (events.js:315:20) at Object.onReceiveStatus
```

**EventStore details**
 - EventStore server version: 21.2.0-buster-slim
 - Operating system: Docker
 - EventStore client version (if applicable): NodeJS, 1.2.1

**Comment by George-Payne** [comment]
Hi Vitek, 

Thank you for the issue, 

I'm having trouble reproducing this, with no `NotHandled` in 100 runs:

``` ts
  test.only("should throw an error if subscription exists", async () => {
    const STREAM_NAME = "stream_name_already_exists";
    const GROUP_NAME = "group_name_already_exists";

    await expect(
      client.createPersistentSubscription(
        STREAM_NAME,
        GROUP_NAME,
        persistentSubscriptionSettingsFromDefaults()
      )
    ).resolves.toBeUndefined();

    await expect(
      client.createPersistentSubscription(
        STREAM_NAME,
        GROUP_NAME,
        persistentSubscriptionSettingsFromDefaults()
      )
    ).rejects.toThrowError(PersistentSubscriptionExistsError);
  });
```

![image](https://user-images.githubusercontent.com/11861797/117627088-19160f00-b178-11eb-90f2-399b3e20e86e.png)


Can you let me know what settings you are passing, or provide some example code that gives this error?

**Comment by vtajzich** [comment]
* We run cluster (3 nodes)
* Following code is used to create a client: 
```
const channelCredentials = {
      insecure: false,
      certChain: configuration.certChain ? fs.readFileSync(configuration.certChain) : undefined,
      privateKey: configuration.privateKey ? fs.readFileSync(configuration.privateKey) : undefined,
      rootCertificate: configuration.rootCertificate ? fs.readFileSync(configuration.rootCertificate) : undefined,
      verifyOptions: {},
    };
    const credentials: Credentials = {
      username: configuration.username,
      password: configuration.password,
    };
    const endpoints = configuration.endpoints;
      const options: GossipClusterOptions = { endpoints: endpoints };
      return new EventStoreDBClient(options, channelCredentials, credentials); 
```

* Code to create a persistent subscription:
```
await this.client.createPersistentSubscription(
        streamName,
        groupName,
        persistentSubscriptionSettingsFromDefaults({
          fromRevision: START,
          resolveLinkTos: true,
          minCheckpointCount: 1,
        }),
      );
```

*

**Comment by George-Payne** [comment]
Hi Vitek,

I'm still unable to reproduce it based on the information you provided. 

If you have time, perhaps you could try to create a minimal reproduction case?

If I were making a guess from looking at the error, is it possible you have multiple copies of `grpc-js` or `@eventstore/db-client` in nested or adjacent `node_module` folders? `expected [..] NotHandled, received NotHandled` sounds like it is making the call from one copy of the library, and creating the error from another, so `message instanceof NotHandled` is returning false. Based on the information you provided I would assume the actual error is `5 NOT_FOUND: Leader info available` (persistent subscriptions must be created on leader.)

George

**Comment by vtajzich** [comment]
@George-Payne I have a same feeling. Several libraries use grpc (we are on GCP, so, logging library etc). 
Could you advice me how to hunt this down?

**Comment by George-Payne** [comment]
If you're using `yarn`, you can use `yarn why` to look at all the versions and dependency tree:
https://classic.yarnpkg.com/en/docs/cli/why
![image](https://user-images.githubusercontent.com/11861797/120184847-bb726100-c211-11eb-94c1-886de161eeca.png)

Then use `resolutions` to force a specific version:
https://classic.yarnpkg.com/en/docs/selective-version-resolutions

If you're using another package manager, they likely have equivalents. 

You could also use `find` (or windows equivalent) to look for versions across your system:
![image](https://user-images.githubusercontent.com/11861797/120185549-a0ecb780-c212-11eb-825e-782b696b988c.png)

**Comment by vtajzich** [comment]
@George-Payne we use `npm`, I tried `find`, however, there is only one grpc-js in `node_modules`

**Comment by George-Payne** [comment]
There is not much more we can do without a reproduction case. 

Could you provide either:

Create a pull request with a failing test added to `src/__test__/persistentSubscription/createPersistentSubscription.test.ts` or a new test file in `src/__test__/extra`. You can find information on running tests [here](https://github.com/EventStore/EventStore-Client-NodeJS#run-tests).

\- or -

A link to a repo with reproduction steps

**Comment by vtajzich** [comment]
I did some testing in our environment. It seems that `nodePreference: "leader"` is the solution.
Maybe, it should be great to make it default for cluster connection.

@George-Payne the test you wrote helped me sort it out. Thanks

**Comment by George-Payne** [comment]
I mentioned this was the likely the error behind the error in this comment: https://github.com/EventStore/EventStore-Client-NodeJS/issues/160#issuecomment-847721385

>  It seems that `nodePreference: "leader"` is the solution.

Be aware that a cluster can re-elect a leader, meaning the leader can change. You should be checking for a `NotLeaderError` and moving your connection to the leader as required. You can find a very basic example of this here:

https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/src/__test__/persistentSubscription/connectToPersistentSubscription.test.ts#L587

However, if you are getting the error `NotHandled, received NotHandled instead` this wont be possible.

**Comment by vtajzich** [comment]
We are not getting the error `NotHandled, received NotHandled instead` anymore. Nothing except the the parameter was changed.

What do you mean that we should be checking the leader election? As long as it is connected it doesn't matter if leader is different node, is it?

**Comment by George-Payne** [comment]
> What do you mean that we should be checking the leader election?

You shouldn't be checking the leader elections, you should be checking for a `NotLeaderError`.

Persistent subscriptions can only be created on the leader node. 
This is why the error telling that you are not connected to the leader goes away when you explicitly request a connection to the leader.
However, it is possible for the leader to change and the client to still be connected to the previous leader. 

The client doesnt handle this internally, and you are expected to handle the error case yourself.
(This may or may not change in the future)

**Comment by vtajzich** [comment]
@George-Payne ok, understood.

What is not clear to me why the `NotHandled is NotHandled` issue went away. It's hard to reproduce though.
