### ISSUE TITLE
Can't use ConnectionTypeOptions with the EventStoreDB constructor

### ISSUE THREAD

**Issue by adriano-di-giovanni** [EventStore/EventStore-Client-NodeJS#166]
It's not possible to do as follows

```typescript
const connectionSettings: ConnectionTypeOptions = { endpoint: 'localhost:2113' };
const client = new EventStoreDBClient(connectionSettings);
```

because no overload matches the call to the `EventStoreDB` constructor.

The overloads could be replaced by a single constructor declaration

```typescript
constructor(connectionSettings: ConnectionTypeOptions, channelCredentials?: ChannelCredentialOptions, defaultUserCredentials?: Credentials)
```

in order to make `ConnectionTypeOptions` more useful.

**Comment by George-Payne** [comment]
Hi Adriano, 

That ought to work fine, as typescript implies the narrowed down type for the overload:
![image](https://user-images.githubusercontent.com/11861797/120328074-c220d700-c2ea-11eb-98a5-bda202941ea6.png)

What version of `@eventstore/db-client` & `typescript` are you using?

**Comment by adriano-di-giovanni** [comment]
Hi @George-Payne ,
@eventstore/db-client 1.2.1
typescript 4.1.5

**Comment by George-Payne** [comment]
Still should work with matching package versions:

![image](https://user-images.githubusercontent.com/11861797/120329489-327c2800-c2ec-11eb-8100-8832089c86b8.png)


Have you simplified the reproduction code? Possibly the error is coming from elsewhere?

**Comment by adriano-di-giovanni** [comment]
Found. I'm using the VSCode version that's 4.3.2

**Comment by adriano-di-giovanni** [comment]
Here is the reproduction code. Thanks for your support.

```typescript
import {
  ConnectionTypeOptions,
  EventStoreDBClient,
} from '@eventstore/db-client';

const connectionSettings: ConnectionTypeOptions = {
  endpoint: 'localhost:2113',
};

function factory(connectionSettings: ConnectionTypeOptions) {
  return new EventStoreDBClient(connectionSettings);
}

const client = factory(connectionSettings);
```

**Comment by George-Payne** [comment]
Thanks for the reproduction case, that's an annoying limitation. 

Unfortunately, with your proposed workaround, we lose some of the type safety from the overloads:

### Currently:
![image](https://user-images.githubusercontent.com/11861797/120619200-0ed7ef80-c45c-11eb-9439-c04fa46bdb37.png)

### No overload:
![image](https://user-images.githubusercontent.com/11861797/120619056-ecde6d00-c45b-11eb-8626-1a01b6629d73.png)

Based on the [related typescript issue] on this, there doesn't seem to be a nice workaround.

I'm going to have to think about what we want to do here, and discuss it with the rest of the team. 

We seem to have three options:

1. Keep things as they are
   - better type safety on direct usage
   - factory functions can cast to any with a comment pointing to this issue
2. Export the individual connection types (`DNSClusterOptions`, `GossipClusterOptions`, `SingleNodeOptions`)
   - keep type safety on direct usage
   - factory functions must choose a single connection type (or cast to any)
3. Collapse the constructor overloads into `ConnectionTypeOptions`
   - worse type safety on direct usage
   - factory functions will work as expected
   
   
If you have any thoughts or other ideas, let me know.
   
[related typescript issue]: https://github.com/microsoft/TypeScript/issues/14107

**Comment by thefringeninja** [comment]
I vote for 2

**Comment by oskardudycz** [comment]
Option 2 sounds to me like a good compromise.

**Comment by adriano-di-giovanni** [comment]
I would go with 2, also removing the `ConnectionTypeOptions` union type unless something like this works

```typescript
type Without<T> = {
  [P in keyof Omit<
    T,
    keyof ClientOptions | keyof DiscoveryOptions
  >]?: undefined;
};

type ConnectionTypeOptions =
  | (DNSClusterOptions &
      Without<GossipClusterOptions> &
      Without<SingleNodeOptions>)
  | (GossipClusterOptions &
      Without<DNSClusterOptions> &
      Without<SingleNodeOptions>)
  | (SingleNodeOptions &
      Without<DNSClusterOptions> &
      Without<GossipClusterOptions>);
```

**Comment by George-Payne** [comment]
I've opened a PR implementing option 2, I also think that is the best option.

> @adriano-di-giovanni commented
>  removing the `ConnectionTypeOptions` union type 

Agreed, but removing it will be a breaking change so I will deprecate it for now, to be removed in the next major.
