### ISSUE TITLE
Example for Persistent Subscription

### ISSUE THREAD

**Issue by vietkute02** [EventStore/EventStore-Client-NodeJS#174]
Hi all,
I've problem when implement persistent subscription pattern. I try to use code from the test case but some thing wrong
I've a stream group by category with name "$ce-interactive_result" then i create Persistent Subscription in this stream 

Code I use

```typescript
    this.overlayResultPersistent = this.eventStoreRepo.getPersistentSubscription('$ce-interactive_result');
    for await (const { event } of this.overlayResultPersistent) {
      if (!event) continue;

      await this.overlayResultPersistent.ack(event.id);
      console.log('ack : ', event.id);
    }
```

I've 2 event in this stream with data is json format, but when event received in subscriber it not json format like this

```
{
  streamId: '$ce-interactive_result',
  id: '22da3205-52cf-43b3-b570-97c241181588',
  revision: 1n,
  type: '$>',
  data: Uint8Array(57) [
     48,  64, 105, 110, 116, 101, 114,  97,  99, 116, 105,
    118, 101,  95, 114, 101, 115, 117, 108, 116,  45, 102,
    100,  52,  55,  52,  51,  55,  52,  45,  54,  57,  57,
     50,  45,  52,  53,  56, 102,  45,  56,  51, 101,  97,
     45,  54,  50,  48, 100,  49,  57,  50,  53,  52,  49,
     98,  55
  ],
  metadata: {
    '$v': '3:-1:1:4',
    '$c': 118595,
    '$p': 118595,
    '$o': 'interactive_result-fd474374-6992-458f-83ea-620d192541b7',
    '$causedBy': '8f2c3bbf-46e5-4d47-9379-62de0c980014'
  },
  isJson: false,
  created: 16257989690005808
}
```
console output: 

```
ack :  7dd2c63d-1e53-4e7c-88f4-8c4e23eb2e2e
ack :  22da3205-52cf-43b3-b570-97c241181588
ack :  7dd2c63d-1e53-4e7c-88f4-8c4e23eb2e2e
ack :  22da3205-52cf-43b3-b570-97c241181588
ack :  7dd2c63d-1e53-4e7c-88f4-8c4e23eb2e2e
ack :  22da3205-52cf-43b3-b570-97c241181588
ack :  7dd2c63d-1e53-4e7c-88f4-8c4e23eb2e2e
ack :  22da3205-52cf-43b3-b570-97c241181588
```

And ack not working event loop push with option retry 10s
What I missing? And has other example for Persistent subscription?
Please help me to resolve this.

PS: I fix this json format with option resolve link to but ack till not working, only packed when reach limit retry

```
{
  "added": "2021-07-09T08:18:57.4513831+00:00",
  "reason": "Reached retry count of 10",
  "subscriptionEventNumber": 2
}
```

version: 20.10.2.0

**Comment by George-Payne** [comment]
Hi Anh,

Unfortunately the only examples for persistent subscriptions are in the tests. The nodejs examples are being worked on for the [documentation](https://developers.eventstore.com/clients/grpc/subscribing-to-streams/persistent-subscriptions.html).

I tried to replicate the behaviour you are seeing, but I don't think I have enough information to do so. 

Could you provide a minimal reproduction example of exactly what you are doing? 
- how the events are added to the stream,
- the options used for creating the persistent subscription


This is my reproduction code:

```ts
import {
  EventStoreDBClient,
  persistentSubscriptionSettingsFromDefaults,
  jsonEvent,
} from "@eventstore/db-client";

const CLOUD_ID = "-";

const STREAM_NAME = "my_stream_name";
const GROUP_NAME = `${STREAM_NAME}-group`;
const PARTITION_PROJECTION_NAME = `${STREAM_NAME}-pro`;

(async () => {
  const client = EventStoreDBClient.connectionString`esdb+discover://admin:changeit@${CLOUD_ID}.mesdb.eventstore.cloud?nodePreference=leader`;

  // Create a projection to link events into a stream:

  await client.enableProjection("$by_category");

  const paritionProjection = `
  fromStream("${STREAM_NAME}")
    .when({
      $any: function(state, ev) {
        linkTo('a-' + ev.data.some, ev)
      }
    });
`;

  await client.createContinuousProjection(
    PARTITION_PROJECTION_NAME,
    paritionProjection,
    { trackEmittedStreams: true }
  );

  // Append two events that will be linked

  const appendResult = await client.appendToStream(STREAM_NAME, [
    jsonEvent({ type: "my_event", data: { number: 1, some: "thing" } }),
    jsonEvent({ type: "my_event", data: { number: 2, some: "thing" } }),
  ]);

  console.log(appendResult);

  // Create a persistent subscription

  await client.createPersistentSubscription(
    "a-thing",
    GROUP_NAME,
    persistentSubscriptionSettingsFromDefaults({
      resolveLinkTos: true,
    })
  );

  console.log("created");

  // connect to persistent subscription

  const overlayResultPersistent = client.connectToPersistentSubscription(
    "a-thing",
    GROUP_NAME
  );

  for await (const { event, ...rest } of overlayResultPersistent) {
    console.log("got event", { event, ...rest });
    if (!event) continue;

    // ack it
    await overlayResultPersistent.ack(event.id);
    console.log("ack : ", event.id);
  }
})();
```
 
 And the output:
 
 ```
 {
  success: true,
  nextExpectedRevision: 1n,
  position: { commit: 1475690n, prepare: 1475690n }
}
created
got event {
  event: {
    streamId: '3',
    id: '73d16300-f5d6-4a25-8dda-680bad6cc6f1',
    revision: 2n,
    type: 'my_event',
    data: { number: 1, some: 'thing' },
    metadata: undefined,
    isJson: true,
    created: 16268627859244348
  },
  link: {
    streamId: 'a-thing',
    id: '63782f8f-09b8-4101-a273-3e153cfdb980',
    revision: 0n,
    type: '$>',
    data: Uint8Array(3) [ 50, 64, 51 ],
    metadata: {
      '$v': '6:-1:0:3',
      '$s': [Object],
      '$causedBy': '73d16300-f5d6-4a25-8dda-680bad6cc6f1'
    },
    isJson: false,
    created: 16268627859539074
  }
}
ack :  73d16300-f5d6-4a25-8dda-680bad6cc6f1
got event {
  event: {
    streamId: '3',
    id: '639c2817-e2e2-40e8-8593-224b974956f9',
    revision: 3n,
    type: 'my_event',
    data: { number: 2, some: 'thing' },
    metadata: undefined,
    isJson: true,
    created: 16268627859244462
  },
  link: {
    streamId: 'a-thing',
    id: '3dd083e2-ee3d-4900-b2db-e0ca3d157fac',
    revision: 1n,
    type: '$>',
    data: Uint8Array(3) [ 51, 64, 51 ],
    metadata: {
      '$v': '6:-1:0:3',
      '$s': [Object],
      '$causedBy': '639c2817-e2e2-40e8-8593-224b974956f9'
    },
    isJson: false,
    created: 16268627859539180
  }
}
ack :  639c2817-e2e2-40e8-8593-224b974956f9
 ```

**Comment by natersgonnanate** [comment]
HI all,

I'm running into the same issue as @vietkute02 and from what I can tell from my tests and code, it seems to be isolated to system projection streams as I have a persistent subscription on my By Event Type stream where the acknowledgement is not registering, and continuously re-trying, but when I create a persistent subscription on the specific entity stream, the acknowledgement works without any change in code.

This is my persistent subscriptions dashboard in the event store UI, you can see that the $et-SourceCreatedEvent stream is indicating there's an unsuccessfully processed event for the stream. Below that is the specific stream for that entity (which had 47 events due to the retries of the event type projection, and all 47 events and acknowledgments went through immediately.

![image](https://user-images.githubusercontent.com/25647001/129256784-d7281e2a-c56c-4a99-b850-3e985568efd5.png)

Here is the section of code that processes the events and send acks and nacks:

`const resolved = (await this.client.subscribeToPersistentSubscription(
        stream,
        subscriptionName,
      )) as ExtendedPersistentSubscription;

      for await (const ev of resolved) {
        if (!ev.event) continue;

        try {
          this.onEvent(ev);
          await resolved.ack(ev.event.id);
        } catch (err) {
          this.logger.error({
            error: err,
            msg: `Error handling event`,
            event: ev,
            stream,
            subscriptionName,
          });
          await resolved.nack('retry', err, ev.event.id);
        }
      }
`

And here is how the event type projection is configured:

![image](https://user-images.githubusercontent.com/25647001/129257515-cc23378a-fc27-42a6-80ab-075911c9180b.png)

Any help or guidance is greatly appreciated. Thanks!

**Comment by George-Payne** [comment]
Hi guys,

The issue you are running in to is that you need to `ack` (or `nack`) with the id of the event that is in the stream you are subscribed to. So, as you are subscribed to the a stream of links, you need to use the id of the link:


 ``` diff
        try {
          this.onEvent(ev);
-         await resolved.ack(ev.event.id);
+         await resolved.ack(ev.link?.id ?? ev.event.id);
        } catch (err) {
          this.logger.error({
            error: err,
            msg: `Error handling event`,
            event: ev,
            stream,
            subscriptionName,
          });
-         await resolved.nack('retry', err, ev.event.id);
+         await resolved.nack('retry', err, ev.link?.id ?? ev.event.id);
        }
```

`ack` and `nack` should be accepting a `resolvedEvent` and choosing the correct `id` for you. I've opened an issue (#204) to track this.

**Comment by natersgonnanate** [comment]
@George-Payne - Thank you!
