### ISSUE TITLE
Move documentation snippets into repo

### ISSUE THREAD

**Issue by George-Payne** [EventStore/EventStore-Client-NodeJS#181]
Snippets are currently here: 
https://github.com/EventStore/documentation/tree/master/samples/grpc/nodejs/samples

Should be moved to `/samples`

Example PR:
https://github.com/EventStore/documentation/pull/258

**Comment by George-Payne** [comment]
Look in to:
- Translating the samples to TS, and compiling to JS. 
- Adding typescript as an language option in the docs
- Testing the snippets in CI (at the very least testing that they compile as TS)

**Comment by oskardudycz** [comment]
@George-Payne, minor, but the default location should be `samples`. Based on what @YoEight told, Rust is opinionated and does not create them in the `samples` folder. That's why we renamed it for the Rust ;)

**Comment by George-Payne** [comment]
> @George-Payne, minor, but the default location should be `samples`. Based on what @YoEight told, Rust is opinionated and does not create them in the `samples` folder. That's why we renamed it for the Rust ;)

Updated
