### ISSUE TITLE
Is it possible to use appendToStream with a "linkTo" event?

### ISSUE THREAD

**Issue by ghindle** [EventStore/EventStore-Client-NodeJS#200]
Is it possible to use appendToStream to create a linkTo event? I've tried the following but to no avail.

```typescript
const linkToEvent = jsonEvent({
    type: "$>",
    data: "2@stream-id"
});
```

**Comment by George-Payne** [comment]
Hi George, 

linkTo events are binary events, so need to be created as follows:

``` tsx
const linkToEvent = binaryEvent({
    type: "$>",
    data: Buffer.from("2@stream-id"),
});
```

I've added a complete example in the tests here: https://github.com/EventStore/EventStore-Client-NodeJS/pull/201

**Comment by ghindle** [comment]
Perfect thank you @George-Payne 🙏
