### ISSUE TITLE
Increase coverage of testing for behaviour around node loss and reconnection

### ISSUE THREAD

**Issue by George-Payne** [EventStore/EventStore-Client-NodeJS#231]
Reconnection tests currently only cover reads and writes. it would be good to expand them out to cover more apis , such as persistent subscriptions.

https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/src/__test__/connection/reconnect.test.ts

_Originally posted by @oskardudycz in https://github.com/EventStore/EventStore-Client-NodeJS/pull/220#discussion_r741920747_

**Comment by Imanghvs** [comment]
I've opened a PR for this issue.
As a regular user of this package I'm really passionate to start making small contributions. If there's any problem with my PR please let me know. I would be happy to correct it.
