### ISSUE TITLE
Looking for a release date for 3.x

### ISSUE THREAD

**Issue by leopoldodonnell** [EventStore/EventStore-Client-NodeJS#260]
The supported release does not support all of the LTS features - eg Persistent Subscriptions to the All Stream.
The node implementation has been in alpha for a while.

When will this be moved to latests supported release?

**Comment by leopoldodonnell** [comment]
Thanks for the update - this is one of the items that is holding back our
upgrade. From a forward planning perspective, should I be looking at early
March or April as a date?

Thanks

**Comment by George-Payne** [comment]
I'd expect early February, but plan for early March. 

Deadlines are now designed and implemented, so the `alpha.2` should be out before long.

**Comment by leopoldodonnell** [comment]
Thanks George, I’ll give the team the heads up.

**Comment by George-Payne** [comment]
v3.0.0 has been released: 
https://github.com/EventStore/EventStore-Client-NodeJS/releases/tag/v3.0.0
https://www.npmjs.com/package/@eventstore/db-client/v/3.0.0
