### ISSUE TITLE
Is there a way how to force release all resources created by client?

### ISSUE THREAD

**Issue by vk185065** [EventStore/EventStore-Client-NodeJS#283]
* We are trying to upgrade NPM to version 3.2.0
* We are running bunch of integration tests which are talking to an EventstoreDB instance
* After upgrading the library and migrating the code our jest tests never finish due to some resource leak
* If I shutdown EventStoreDB (e.g. it closes all the connections) - the tests will finish immediately
* As such it suggests there remains some open handle but I cannot find a way how to properly shutdown that part of the NPM...

Any suggestion?

**Comment by George-Payne** [comment]
Hi Vladimir,

The open handle is from the new batch append functionality, it keeps a connection open to skip the handshake with the server (for faster append speeds).

I'll add a few fixes for this:

- Add a `dispose` method to close all connections
- Make batch append close the connection if you haven't used it for a specified length of time.

----

> our jest tests never finish

If you want a dirty workaround for the time being jest has a `--forceExit` flag to forcibly close all processes at the end of a test.

**Comment by voloda** [comment]
@George-Payne - thanks for quick response. We are trying to avoid the dirty one - having dispose would work great for us.

Do you have any estimate when the change might be available? I do not necessarily need auto-expiration.

**Comment by George-Payne** [comment]
> Do you have any estimate when the change might be available?

I've opened a PR which adds a `dispose` method https://github.com/EventStore/EventStore-Client-NodeJS/pull/285 and I'll put out a release with it once it's merged. I'd expect that to be some time next week (assuming no issues are found with it etc).

If you have time, it would be very helpful for you to pull it down and confirm that calling `dispose` fixes your hanging tests.

**Comment by George-Payne** [comment]
v3.3.0 has been released containing the dispose method:
https://www.npmjs.com/package/@eventstore/db-client/v/3.3.0

**Comment by vk185065** [comment]
Thanks - I was out for couple of days. I gave it a try and it seems to work just fine now. Appreciated...
