### ISSUE TITLE
Retrieving batch of events from catchup subscriptions

### ISSUE THREAD

**Issue by vk185065** [EventStore/EventStore-Client-NodeJS#295]
Is there a way how I could get a batch of 1..N events from a catchup subscription?

I would really get a sequence of events as an array with range 1..N where N is the max count so I can process these in-order of arrival.

I found a way how to do it thru event handler callback but it apparently does not have any guarantee in which order events arrive...

If I had such ability I can apply domain knowledge to process events even faster...

Thanks

**Comment by alexeyzimarev** [comment]
You always get events in order, as it is a gRPC stream, and the handler callback is called sequentially for each event. Until the handler returns, the previous event is not delivered.

You can batch in the handler itself.

**Comment by vk185065** [comment]
Thanks. The challenge with this approach is that I do not know when the last item of batch arrived... As I mentioned - there are ways how to deal with it but it has its own complexity, so getting the whole batch might be helpful...
