### ISSUE TITLE
created is not a javascript safe integer

### ISSUE THREAD

**Issue by nicdex** [EventStore/EventStore-Client-NodeJS#318]
At https://github.com/EventStore/EventStore-Client-NodeJS/blob/master/src/utils/convertGrpcEvent.ts#L118

You use parseInt to parse the created metadata value, but it's containing a 64bit integer represented as a string. 
The created metadata contains .Net DateTime Ticks value, which has a 100ns precision (10000 ticks = 1ms)
It returns an integer that is not safe according to Number.MAX_SAFE_INTEGER.
It might be best to use bigint as you do for other 64bit values.

**Comment by George-Payne** [comment]
Hi Nicolas, 

Thanks for the issue, great spot. 
All of the other clients convert this to a (language equivalent of) `Date`, so I'll do the same here.

We are trying to move away from passing around ticks, but this one seems to have slipped through the cracks, so I've brought this up with the team and also opened an upstream issue: https://github.com/EventStore/EventStore/issues/3630.

**Comment by George-Payne** [comment]
`v5.0.0` has been released, including this fix.

https://www.npmjs.com/package/@eventstore/db-client/v/5.0.0
https://github.com/EventStore/EventStore-Client-NodeJS/releases/tag/v5.0.0
