### ISSUE TITLE
Gracefull shutdown

### ISSUE THREAD

**Issue by matchish** [EventStore/EventStore-Client-NodeJS#320]
What is the correct way for gracefull shutdown to close all connections and subscriptions?

**Comment by George-Payne** [comment]
Hi Sergey,

You can use `client.dispose()` (added in v3.3.0) to close all streaming reads / writes / duplex.

The (current) list of streaming methods are:
- `subscribeToPersistentSubscriptionToAll`
- `subscribeToPersistentSubscriptionToStream`
- `readAll`
- `readStream`
- `subscribeToAll`
- `subscribeToStream`
- `appendToStream` (if batch append is used, and the stream is internally managed)

You'll receive an `end` event on these streams when `dispose` is called. 

e.g. :

``` ts
client
  .subscribeToStream("mystream")
  .on("error", (e) => console.error("error", e))
  .on("data", (e) => console.log("event", e))
  .on("end", () => console.log("end"))

// "event" { ... }
// "event" { ... }
// ...

await client.dispose();

// "end"
```

George
