### ISSUE TITLE
Please ship a sourcemap

### ISSUE THREAD

**Issue by shellscape** [EventStore/EventStore-Client-NodeJS#325]
That's the request. Please produce a sourcemap and ship it in the NPM package. We're trying to debug an "UNAVAILABLE" error and it's quite the PITA without the sourcemap.

**Comment by George-Payne** [comment]
Hi Andrew, 

Thanks for the issue, I've made a PR to generate them. I'll put out a patch release once it's reviewed & merged.

> We're trying to debug an "UNAVAILABLE" error

In the mean time, if you haven't already, you can enable debug logging by setting the `DEBUG` environment variable to `"esdb:*"`, might help you see what's going on.

https://github.com/EventStore/EventStore-Client-NodeJS#debugging

Also, if it helps, the `UNAVAILABLE` error is mapped from the GRPC `UNAVAILABLE` status code (14). https://grpc.github.io/grpc/core/md_doc_statuscodes.html 

It will usually means that the node that the client has connected has gone down, and you should retry whatever you were doing. The client will automatically reconnect to another node (using your `nodePreference`) but won't retry or resume whatever you were doing when the error occurred.

**Comment by George-Payne** [comment]
v5.0.1 has been released containing sourcemaps
https://www.npmjs.com/package/@eventstore/db-client/v/5.0.1
