### ISSUE TITLE
6.2.0 doesn't include a dist folder

### ISSUE THREAD

**Issue by TheDevMinerTV** [EventStore/EventStore-Client-NodeJS#376]
The package.json file points `main` and `types` towards a directory called `dist`, but this doesn't exist in v6.2.0 of `@eventstore/db-client`.
v6.1.0 had this directory.

References:
- https://www.npmjs.com/package/@eventstore/db-client?activeTab=code
- https://www.npmjs.com/package/@eventstore/db-client/v/6.1.0?activeTab=code

**Comment by w1am** [comment]
Hi. Thanks for letting us know. I just published a minor version that includes the dist folder to NPM.

**Comment by TheDevMinerTV** [comment]
The packages in this repo haven't updated their version yet, this might bite you on the next release.

**Comment by w1am** [comment]
I'll update them in a pull request :)
