### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by yreynhout** [EventStore/EventStore-Client-NodeJS#390]
The homepage link on [npmjs](https://www.npmjs.com/package/@eventstore/db-client) is broken (also appears in VsCode flyover).

![image](https://github.com/user-attachments/assets/63a50427-96f0-487a-a4f3-4169137af995)

**Comment by w1am** [comment]
The [homepage link](https://developers.eventstore.com/clients/grpc/getting-started.html?codeLanguage=NodeJS) issue appears to have been resolved in the docs on its own
