### ISSUE TITLE
There doesn't appear to be straightforward way to provide custom metadata

### ISSUE THREAD

**Issue by leopoldodonnell** [EventStore/EventStore-Client-NodeJS#40]
CustomMetadata is provided in

```
 export namespace ProposedMessage {
        export type AsObject = {
            id?: shared_pb.UUID.AsObject,
            metadataMap: Array<[string, string]>,
            customMetadata: Uint8Array | string,
            data: Uint8Array | string,
        }
    }
```

but `writeEventsToStream` does not appear to offer a way to include `customMetadata`.

It isn't clear what the preferred approach to setting metadata is. Important metadata includes such things as JsonSchema version.

Am I missing something?

**Comment by leopoldodonnell** [comment]
Perhaps it is expected that metadata is up to the implementor and `EventData` should be used?

**Comment by hayley-jean** [comment]
Fixed in https://github.com/EventStore/EventStore-Client-NodeJS/pull/41
