### ISSUE TITLE
Persistent subscription connection failed with NOT_FOUND: Leader info available

### ISSUE THREAD

**Issue by juanchristensen** [EventStore/EventStore-Client-NodeJS#82]
We are seeing an error with persistent subscription connections on our EventStore Cloud cluster.

We are using the v0.0.0-alpha.7 release.
Non-persistent subscriptions work correctly.

We are initializing the client with the 3 GRPC addresses shown in the cloud console.

`Connection.builder().gossipClusterConnection(clusterAddresses)`

`  esdb:connection Importing root certificate from path "/etc/ssl/certs/ca-certificates.crt" +0ms
  esdb:connection Using credentials {
  esdb:connection   insecure: false,
  esdb:connection   rootCertificate: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 48 30 7a 43 43 42 62 75 67 41 77 49 42 41 67 49 49 58 73 ... 198366 more bytes>,
  esdb:connection   privateKey: undefined,
  esdb:connection   certChain: undefined,
  esdb:connection   verifyOptions: undefined
  esdb:connection } +3ms
  esdb:command CreatePersistentSubscription: {
  esdb:command   requiresLeader: false,
  esdb:command   stream: 'test',
  esdb:command   group: 'eventStorePoc',
  esdb:command   resolveLink: false,
  esdb:command   extraStats: false,
  esdb:command   revision: 0n,
  esdb:command   messageTimeout: 30000,
  esdb:command   maxRetryCount: 10,
  esdb:command   checkpointAfter: 2000,
  esdb:command   minCheckpointCount: 10,
  esdb:command   maxCheckpointCount: 1000,
  esdb:command   maxSubscriberCount: 0,
  esdb:command   liveBufferSize: 500,
  esdb:command   readBatchSize: 20,
  esdb:command   historyBufferSize: 500,
  esdb:command   strategy: 'round_robin',
  esdb:command   credentials: { username: 'xxxxxxx', password: 'xxxxxxxx' }
  esdb:command } +0ms
  esdb:command:grpc CreatePersistentSubscription: {
  esdb:command:grpc   options: {
  esdb:command:grpc     streamIdentifier: { streamname: 'dGVzdA==' },
  esdb:command:grpc     groupName: 'eventStorePoc',
  esdb:command:grpc     settings: {
  esdb:command:grpc       resolveLinks: false,
  esdb:command:grpc       revision: '0',
  esdb:command:grpc       extraStatistics: false,
  esdb:command:grpc       maxRetryCount: 10,
  esdb:command:grpc       minCheckpointCount: 10,
  esdb:command:grpc       maxCheckpointCount: 1000,
  esdb:command:grpc       maxSubscriberCount: 0,
  esdb:command:grpc       liveBufferSize: 500,
  esdb:command:grpc       readBatchSize: 20,
  esdb:command:grpc       historyBufferSize: 500,
  esdb:command:grpc       namedConsumerStrategy: 1,
  esdb:command:grpc       messageTimeoutTicks: '0',
  esdb:command:grpc       messageTimeoutMs: 30000,
  esdb:command:grpc       checkpointAfterTicks: '0',
  esdb:command:grpc       checkpointAfterMs: 2000
  esdb:command:grpc     }
  esdb:command:grpc   }
  esdb:command:grpc } +0ms
  esdb:connection Createing client for CreatePersistentSubscription +25ms
  esdb:connection Connecting to http://xxxxxxxxxxxxxx-0.mesdb.eventstore.cloud:2113 +0ms
NotLeaderError: 5 NOT_FOUND: Leader info available
    at Object.exports.convertToCommandError (/app/node_modules/@eventstore/db-client/dist/utils/CommandError.js:239:20)
    at Object.callback (/app/node_modules/@eventstore/db-client/dist/command/persistentSubscription/CreatePersistentSubscription.js:217:50)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:334:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
    at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:237:24
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 5,
  _raw: Error: 5 NOT_FOUND: Leader info available
      at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/src/call.ts:81:24)
      at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client.ts:334:36)
      at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:434:34)
      at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/src/client-interceptors.ts:397:48)
      at /app/node_modules/@grpc/grpc-js/src/call-stream.ts:237:24
      at processTicksAndRejections (internal/process/task_queues.js:79:11) {
    code: 5,
    details: 'Leader info available',
    metadata: Metadata { internalRepr: [Map], options: {} }
  },
  type: 'not-leader',
  leader: {
    address: 'xxxxxxxxxxxxxxxxx-2.mesdb.eventstore.cloud',
    port: 2113
  }
}`

**Comment by George-Payne** [comment]
Hi Juan, 

Persistent subscriptions require a connection to the leader node. If you attempt to use them on a follower node, you will get back an error pointing you towards the current leader (the error you are seeing). 

The client doesnt handle this internally, and you are expected to handle the error case yourself. 
(This may or may not change in the future)

I've added a rather basic example of how you can handle this error here:

https://github.com/EventStore/EventStore-Client-NodeJS/pull/83/commits/efe0658ceccf42216aa73107f782aa19327bfe8c#diff-8313a8887d1c59089197879f01013691409ddf72ec6e6896218dc48e2a18659fR463
