### ISSUE TITLE
Cannot find type definition file for 'debug'

### ISSUE THREAD

**Issue by natersgonnanate** [EventStore/EventStore-Client-NodeJS#91]
Hi, running into the following error when trying to build:

```
node_modules/@eventstore/db-client/dist/utils/debug.d.ts:1:23 - error TS2688: Cannot find type definition file for 'debug'.

1 /// <reference types="debug" />
```
There may be a ts compiler config to workaround or ignore the issue, but wanted to verify.

**Comment by George-Payne** [comment]
Thanks for making me aware of this, I'll have to figure out a way to include these types. 

In the mean time, they are provided by [`@types/debug`](https://www.npmjs.com/package/@types/debug) so you can add it to your dev dependancies to work around it.

**Comment by natersgonnanate** [comment]
Thanks @George-Payne!

**Comment by George-Payne** [comment]
@natersgonnanate  The dev dependancy is no-longer required, as of [0.0.0-alpha.10](https://www.npmjs.com/package/@eventstore/db-client/v/0.0.0-alpha.10)
