### ISSUE TITLE
createOneTimeProjection should allow naming it on creation

### ISSUE THREAD

**Issue by pabSec** [EventStore/EventStore-Client-NodeJS#95]
This should be allowed in order to control the one time projections created using the client right?

**Comment by George-Payne** [comment]
Hello,

This is currently missing upstream, you can find the corresponding issue here:

https://github.com/EventStore/EventStore/issues/2733

There also isn't currently a good work around. 

You can find the names of all of the one time projections using `client.listOneTimeProjections()`.

**Comment by oskardudycz** [comment]
@pabSec, in the next gRPC client release, we plan to remove support for the one-time projection. We understand that this might be useful for the specific cases, but we'd like to replace it with something more reliable and easier to use. could you provide more details about your use case? We could try to give more general guidance.

**Comment by George-Payne** [comment]
`v3.0.0` has been released, removing support for one-time projections. I'll close this issue as it is no longer actionable.
